### ISSUE TITLE
QA_Preparation of Sols_Experiment_mouse-pointer-functionality-glass-rod

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#1]
Defect Description :
In the experiment section, the functionality of the mouse is improper. The cursor should change only when the mouse is placed on the Glass rod. Then the click functionality should begin. 

Actual Result :
In the experiment section, the functionality of the mouse is improper. The cursor should change only when the mouse is placed on the Glass rod. Then on click the functionality should begin. Instead in the converted experiment the cursor and the functionality both are happening on an inappropriate place.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i18](https://user-images.githubusercontent.com/13479177/28200229-63e099f2-6888-11e7-81d5-71194931cf1b.png)

**Comment by blazingeagle1002** [comment]
issue approved by Lalit sir

**Comment by BSravanthi** [comment]
Closed
