### ISSUE TITLE
QA_Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles_Experiment_solution-color-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#10]
Defect Description :
In the experiment section, the color of the solution in the conical flask is differing from the original experiment.

Actual Result :
In the experiment section, the color of the solution in the conical flask is differing from the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i24](https://user-images.githubusercontent.com/13479177/28312779-feead934-6bd1-11e7-9d99-1f3af5f0ec34.png)

**Comment by blazingeagle1002** [comment]
Issue approved by Lalit sir

**Comment by BSravanthi** [comment]
closed
