### ISSUE TITLE
QA_Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems_experiment_beaker

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#11]
Defect Description :
In the experiment section, the beaker that contains Fe(OH)3 is not clearly visible in the converted experiment.

Actual Result :
In the experiment section, the beaker that contains Fe(OH)3 is not clearly visible in the converted experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i25](https://user-images.githubusercontent.com/13479177/28313856-faa282ba-6bd5-11e7-899c-9bcb818c226f.png)

**Comment by blazingeagle1002** [comment]
Issue approved by Lalit sir

**Comment by BSravanthi** [comment]
closed
