### ISSUE TITLE
QA_Preparation of Sols_Experiment_Water-label_inconsistancy

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#18]
Defect Description :
In the experiment section, we observed that the water label on the beaker is not appearing after the water is poured from the jar when we refresh the experiment page for several times. To maintain the consistency need to fix the issue

Actual Result :
In the experiment section, we observed that the water label on the beaker is not appearing after the water is poured from the jar when we refresh the experiment page for several times. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
**N/A**

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #18
