### ISSUE TITLE
QA_Preparation of Sols_Experiment_functionality-of-glass-rod

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#19]
Defect Description :
In the experiment section, the functionality of the glass rod to mix the powder and the water is varying from the original experiment. In the original experiment, the click functionality is enabled to the rod is different in the original and converted experiments.  

Actual Result :
In the experiment section, the functionality of the glass rod to mix the powder and the water is varying from the original experiment. In the original experiment, the click functionality is enabled to the rod is different in the original and converted experiments. The click functionality is enabled on the tip (maybe a little down) on the rod in the converted experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
**N/A**

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #19
