### ISSUE TITLE
QA_Preparation of Sols_Experiment_size-of-the-conical-flask-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#20]
Defect Description :
In the experiment section, the size of the conical flask is differing from the original experiment.

Actual Result :
In the experiment section, the size of the conical flask is differing from the original experiment. The width of the flask is little more and height of the flask is little less

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i005](https://user-images.githubusercontent.com/13479177/33648985-223c3d32-da82-11e7-8c8d-24ebdc342cfa.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #20
