### ISSUE TITLE
QA_Preparation of Sols_Experiment_magnetic-bead

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#22]
Defect Description :
In the experiment section, the magnetic bead is differing from the original experiment.

Actual Result :
In the experiment section, the magnetic bead is differing from the original experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i007](https://user-images.githubusercontent.com/13479177/33649633-a8c1bbaa-da84-11e7-8066-539e16af64da.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #22
