### ISSUE TITLE
QA_Preparation of Sols_Experiment_outline-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#24]
Defect Description :
In the experiment section, the outline of the experiment is missing in the converted experiment which is there in the original experiment.

Actual Result :
In the experiment section, the outline of the experiment is missing in the converted experiment which is there in the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_csc_i009](https://user-images.githubusercontent.com/13479177/33701055-d9c392d2-db42-11e7-947b-d98331749ca2.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #24
