### ISSUE TITLE
QA_Preparation of Sols_Experiment_direction-strip_font-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#25]
Defect Description :
In the experiment section, the font style in the direction strip is differing front the original experiment.

Actual Result :
In the experiment section, the magnetic bead is differing from the original experiment. To maintain the consistency need to maintain the same font size and style.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_csc_i009](https://user-images.githubusercontent.com/13479177/33701370-7a4ef88a-db44-11e7-9b18-a441d62f3274.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #25
