### ISSUE TITLE
QA_Preparation of Sols_Experiment_Pippette-label-placing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#27]
Defect Description :
In the experiment section, the label for pippette is differing from the original experiment. 

Actual Result :
In the experiment section, the label for pippette is differing from the original experiment. In the original experiment, the label is on the right side of the screen. whereas in the converted experiment, the same is placed on the left side. Please refer the screenshot for reference. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i011](https://user-images.githubusercontent.com/13479177/33702666-a1f911f8-db4a-11e7-96ef-ef13e9841fd2.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed #27
