### ISSUE TITLE
QA_Preparation of Sols_Experiment_border-around the experoment is missed.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#28]
Defect Description :
In the experiment section, the border around the experiment table is missed which is present in the original experiment.

Actual Result :
In the experiment section, the border around the experiment table is missed which is present in the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i011](https://user-images.githubusercontent.com/13479177/33867010-d86c033e-df1f-11e7-853f-32ece477b1f0.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
