### ISSUE TITLE
QA_Preparation of Sols_Experiment_placing of the arrow image is differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#29]
Defect Description :
In the experiment section, the placing of the arrow image is differing from the original experiment.

Actual Result :
In the experiment section, the placing of the arrow image is differing from the original experiment. Please find the attachments for the reference.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i012](https://user-images.githubusercontent.com/13479177/33867304-c62e7948-df21-11e7-8d4e-6e2788588b82.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
