### ISSUE TITLE
QA_Critical Micelle Concentration_experiment_title of the table is missed.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#30]
Defect Description :
In the experiment section, the title of the experiment is missed. Which is present in the original experiment.

Actual Result :
In the experiment section, the title of the experiment is missed. Which is present in the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i013](https://user-images.githubusercontent.com/13479177/33868242-db5999aa-df27-11e7-8c9b-27b897f65d4d.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
