### ISSUE TITLE
QA_Critical Micelle Concentration_experiment_slider-bar-ui-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#31]
Defect Description :
In the experiment section, the UI of the slider bar is differing from the original experiment. 

Actual Result :
In the experiment section, the UI of the slider bar is differing from the original experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i013](https://user-images.githubusercontent.com/13479177/33868371-7f06e224-df28-11e7-8d52-a387fc276b1a.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
