### ISSUE TITLE
QA_Critical Micelle Concentration_experiment_sample-solution-containers-images-are-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#32]
Defect Description :
In the experiment section, the images for the sample solution beakers are differing from the original experiment.

Actual Result :
In the experiment section, the images for the sample solution beakers are differing from the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i014 b](https://user-images.githubusercontent.com/13479177/33868964-2ddd6932-df2c-11e7-8b34-0808f8e5a6ce.png)
![qa_csc_i014 a](https://user-images.githubusercontent.com/13479177/33868965-2e26d05e-df2c-11e7-842e-29114488faf9.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
