### ISSUE TITLE
QA_Critical Micelle Concentration_experiment_image-finishing-needs-to-be-improved

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#33]
Defect Description :
In the experiment section, the images need to have a clear and sharp finishing for a better look and feel of the experiment. This can be done by adding borders to few images and by zooming out for few other images.

- In the meter, the font and numbers are not clear. 
- The Partition lines for the concentration levels of the solution are not given at the slider bar. The numbers are also blurred. 

Actual Result :
In the experiment section, the images need to have a clear and sharp finishing for a better look and feel of the experiment. This can be done by adding borders to few images and by zooming out for few other images.

- In the meter, the font and numbers are not clear. 
- The Partition lines for the concentration levels of the solution are not given at the slider bar. The numbers are also blurred. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i015 b](https://user-images.githubusercontent.com/13479177/33869278-e6d12716-df2d-11e7-8b14-12c49e0598bb.png)
![qa_csc_i015 a](https://user-images.githubusercontent.com/13479177/33869280-e71e4bc2-df2d-11e7-87b0-66b0ac8abd54.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
