### ISSUE TITLE
QA_Critical Micelle Concentration_experiment_border-around the experoment is missed

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#38]
Defect Description :
In the experiment section, the border around the experiment table is missed which is present in the original experiment.

Actual Result :
In the experiment section, the border around the experiment table is missed which is present in the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i017 b](https://user-images.githubusercontent.com/13479177/33875980-18f4b80e-df4a-11e7-8c5b-d55299de74c5.png)
![qa_csc_i017 a](https://user-images.githubusercontent.com/13479177/33875981-1937f01a-df4a-11e7-9b5c-e24b90874ba5.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
