### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_image-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#39]
Defect Description :
In the experiment section, the "Structure of soap molecule" experiment, the soap molecule image is differing from the original experiment. 

Actual Result :
In the experiment section, the "Structure of soap molecule" experiment, the soap molecule image is differing from the original experiment.  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i018](https://user-images.githubusercontent.com/13479177/33878795-74c8a282-df52-11e7-823a-4221199fd8f2.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
