### ISSUE TITLE
QA_ Determination of Critical Micelle Concentration (CMC) of a Surfactant_Experiment_slider-bar-should-be-brighter

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#4]
Defect Description :
In the experiment section, the slider bar is invisible due to the lesser brightness. 

Actual Result :
In the experiment section, the slider bar is invisible due to the lesser brightness. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i19](https://user-images.githubusercontent.com/13479177/28303323-36bdeaa8-6bb0-11e7-9cb9-0fd8c3411cd2.png)

**Comment by blazingeagle1002** [comment]
Issue approved by Lalit sir

**Comment by BSravanthi** [comment]
closed
