### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_title-font-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#40]
Defect Description :
In the experiment section, the font of the heading is differing from the original experiment. 

Actual Result :
In the experiment section, the font of the heading is differing from the original experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i019](https://user-images.githubusercontent.com/13479177/33921796-3fdadbf4-dfec-11e7-9cd6-49c6005a8761.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
