### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_border-is-not-given

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#41]
Defect Description :
In the experiment section, the border is missed at the main screen and the 3 experiment screens of the experiment.

Actual Result :
In the experiment section, the border is missed at the main screen and the 3 experiment screens of the experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i020](https://user-images.githubusercontent.com/13479177/33921987-9ec8e7ea-dfed-11e7-8d6d-193a6b296684.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
