### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_hilghting-the-options

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#42]
Defect Description :
In the experiment section, in the original experiment - when the mouse hovers on the 2 different experiments the options are getting hi-lighted. Whereas in the converted one, observed that this function is not present.

Actual Result :
In the experiment section, in the original experiment - when the mouse hovers on the 2 different experiments the options are getting hi-lighted. Whereas in the converted one, observed that this function is not present.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i021](https://user-images.githubusercontent.com/13479177/33922480-1881010a-dff1-11e7-940a-2c1b77685ffc.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
