### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_table-image-size-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#43]
Defect Description :
In the experiment section, for all the 3 experiment sections - the size of the table image is differing from the original experiment.

Actual Result :
In the experiment section, for all the 3 experiment sections - the size of the table image is differing from the original experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i22 b](https://user-images.githubusercontent.com/13479177/33923111-3d81c616-dff5-11e7-8ba9-0c6b84b6455a.png)
![qa_csc_i022 a](https://user-images.githubusercontent.com/13479177/33923112-3dc98172-dff5-11e7-9e22-a99b99b81e8a.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
Closed
