### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_Micelle-formation_animation-for-spoon

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#49]
Defect Description :
In the "Micelle formation" experiment section, the animation for the spoon that pours detergent for the first time in the water is differing from the original experiment. In the original experiment, the spoon will disappear once the detergent is transferred into the water. Whereas, in the converted experiment the spoon will disappear once it reaches to the beaker. 

Actual Result :
In the "Micelle formation" experiment section, the animation for the spoon that pours detergent for the first time in the water is differing from the original experiment. In the original experiment, the spoon will disappear once the detergent is transferred into the water. Whereas, in the converted experiment the spoon will disappear once it reaches to the beaker. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i026 a](https://user-images.githubusercontent.com/13479177/33926904-0d21906c-e006-11e7-9be7-84de8937b655.png)
![qa_csc_i026 b](https://user-images.githubusercontent.com/13479177/33926917-166b54aa-e006-11e7-9f0d-90879bf91db1.png)

**Comment by BSravanthi** [comment]
Not fixed yet. Hence reopening

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue since i didn't even have any kind of resources to develop the experiment.

**Comment by BSravanthi** [comment]
Closed
