### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_Micelle-formation_stirrer-image-color-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#51]
Defect Description :
In the "Micelle formation" experiment section, the color of the stirrer image is differing from the original experiment.

Actual Result :
In the "Micelle formation" experiment section, the color of the stirrer image is differing from the original experiment. Refer the screenshot. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i027](https://user-images.githubusercontent.com/13479177/33928048-686ccd70-e00a-11e7-9ab8-6c09aa84bd04.png)

**Comment by BSravanthi** [comment]
The issue still persists.

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
