### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_Micelle-formation_animation-differes-when-CMC-is-achieved

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#52]
Defect Description :
In the "Micelle formation" experiment section, the animation for the molecules when CMC is achieved is differing. The placing  and the speed of the molecules are different in the converted experiment.

Actual Result :
In the "Micelle formation" experiment section, the animation for the molecules when CMC is achieved is differing. The placing  and the speed of the molecules are different in the converted experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i028 a](https://user-images.githubusercontent.com/13479177/33930283-611c24c8-e012-11e7-89d5-c2f8993c3710.png)
![qa_csc_i028](https://user-images.githubusercontent.com/13479177/33930284-616181c6-e012-11e7-8c15-6b628451e508.png)

**Comment by BSravanthi** [comment]
The issue still persists. Hence reopened...

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
