### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_image-size-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#56]
Defect Description :
In the experiment section, the image size is differing from the original experiment. The conical flask size is differing.

Actual Result :
In the experiment section, the image size is differing from the original experiment. The conical flask size is differing.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_csc_i031 a](https://user-images.githubusercontent.com/13479177/33935231-2e66013e-e021-11e7-89f4-f5780400bf82.png)
![qa_csc_i031 b](https://user-images.githubusercontent.com/13479177/33935276-4be1fdd0-e021-11e7-96db-333035ac8cfa.png)

**Comment by BSravanthi** [comment]
Can be modified further.

**Comment by BSravanthi** [comment]
Keeping the issue on hold and moving further for deployment as this issue is not a show stopper for deployment

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
