### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_animation-for-stirrer(salt-solution)

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#57]
Defect Description :
In the experiment section, the animation for the stirrer is not clearly visible.

Actual Result :
In the experiment section, the animation for the stirrer is not clearly visible.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i030 b](https://user-images.githubusercontent.com/13479177/33935411-da43f3b2-e021-11e7-8c94-a69d48ff2469.png)
![qa_csc_i030 a](https://user-images.githubusercontent.com/13479177/33935412-da97c74e-e021-11e7-9b86-32e29733783a.png)

**Comment by BSravanthi** [comment]
Still, the issue persists. Hence reopening the issue. Whereas can move further for deployment.

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
