### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_animation-for-stirrer(Sugar-solution)

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#58]
Defect Description :
In the experiment section, the animation for the stirrer is not clearly visible.

Actual Result :
In the experiment section, the animation for the stirrer is not clearly visible.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

The attachment is from original experiment.

![qa_csc_i033 a](https://user-images.githubusercontent.com/13479177/33935778-23a877a2-e023-11e7-910f-f5710e682ee7.png)

**Comment by BSravanthi** [comment]
The issue still persists. Reopened but moving further for deployment.

![qa_csc_i050](https://user-images.githubusercontent.com/13479177/34242881-07850c76-e644-11e7-9811-3558218caaec.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore the issue.

**Comment by BSravanthi** [comment]
closed
