### ISSUE TITLE
QA_ Determination of Critical Micelle Concentration (CMC) of a Surfactant_Experiment_value-of-the-concentration-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#6]
Defect Description :
In the experiment section, the value of the solution with 0 concentration is differing.
Actual Result :
In the experiment section, the value of the solution with 0 concentration is differing. In the original experiment, value for this concentration is 2.42 where as in the converted experiment, the value is '0'.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i21](https://user-images.githubusercontent.com/13479177/28305269-a389ff8e-6bb8-11e7-8ef7-3403df3d7c0c.png)

**Comment by blazingeagle1002** [comment]
Issue is fixed

**Comment by BSravanthi** [comment]
closed
