### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_animation-for-stirrer(soap-solution)

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#62]
Defect Description :
In the experiment section, the animation for the stirrer is not clearly visible.

Actual Result :
In the experiment section, the animation for the stirrer is not clearly visible.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_csc_i036 a](https://user-images.githubusercontent.com/13479177/33978546-49353c78-e0c6-11e7-9b34-076c28ec04bf.png)
![qa_csc_i036 b](https://user-images.githubusercontent.com/13479177/33978548-499a974e-e0c6-11e7-897a-eb807bc18ee8.png)

**Comment by BSravanthi** [comment]
Still persisted. Moving further

![qa_csc_i0051](https://user-images.githubusercontent.com/13479177/34243845-c48516fa-e648-11e7-97f1-f8e442251276.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore such stirring issues.

**Comment by BSravanthi** [comment]
Closed
