### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_UI-of-the-beaker(soap-solution)

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#63]
Defect Description :
In the experiment section, the UI of the soap solution beaker is improper. The foam and the solution are not clearly visible compared to the original experiment.

Actual Result :
In the experiment section, the UI of the soap solution beaker is improper. The foam and the solution are not clearly visible compared to the original experiment

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_csc_i038 a](https://user-images.githubusercontent.com/13479177/33978654-cfb4dff6-e0c6-11e7-826e-a5d6ae184974.png)
![qa_csc_i038 b](https://user-images.githubusercontent.com/13479177/33978655-cfedce42-e0c6-11e7-9b9f-1de8e7cda32f.png)

**Comment by BSravanthi** [comment]
Still persists. Moving further

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
