### ISSUE TITLE
QA_Demonstration of Tyndall Effect_experiment_border-around-the-experiment

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#68]
Defect Description :
In the experiment section, the border is missed around the experiment space.

Actual Result :
In the experiment section, the border is missed around the experiment space.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i042 a](https://user-images.githubusercontent.com/13479177/33984284-0f973842-e0dd-11e7-8016-2d540cc74448.png)
![qa_csc_i042 b](https://user-images.githubusercontent.com/13479177/33984285-0fcb46b4-e0dd-11e7-81a9-75a9925c90dc.png)

**Comment by BSravanthi** [comment]
Not fixed. Still moving further

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
