### ISSUE TITLE
QA_Demonstration of Surface Effects on Chemical Properties of Finely Divided Particles_UI-differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#69]
Defect Description :
In the experiment section, the UI of the experiment is differing from the original experiment. Observed the following differences:
1. Size of the objects. Height and width wise.
2. Display of Procedure steps placing is differing. 
3.  Title of the experiment's size is different.  

Actual Result :
In the experiment section, the UI of the experiment is differing from the original experiment. Observed the following differences:
1. Size of the objects. Height and width wise.
2. Display of Procedure steps placing is differing. 
3.  Title of the experiment's size is different.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i043 a](https://user-images.githubusercontent.com/13479177/33987541-42ef1340-e0e7-11e7-88aa-0354dc01909a.png)
![qa_csc_i043 b](https://user-images.githubusercontent.com/13479177/33987542-43431634-e0e7-11e7-8a4c-7467b8ffecdf.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
