### ISSUE TITLE
QA_ Determination of Critical Micelle Concentration (CMC) of a Surfactant_Experiment_slider-functionality

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#7]
Defect Description :
In the experiment section, the functionality of the slider is differing from the original experiment.

Actual Result :
In the experiment section, the functionality of the slider is differing from the original experiment. 

1) In the original experiment to change the concentration the slider can be dragged or can be clicked on the bar. But in the converted experiment, we can only click on the desired concentration to select particular concentration. Can not drag the slider.

2) When hovered on the slider the slide pointer is high lighted in the original experiment. Where as in the converted experiment when the mouse is hovered the slide pointer is not getting high lighted. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_csc_i22](https://user-images.githubusercontent.com/13479177/28309361-bceb9876-6bc6-11e7-995c-a13a3ddba4da.png)

**Comment by blazingeagle1002** [comment]
Issue approved by Lalit sir

**Comment by BSravanthi** [comment]
Closed
