### ISSUE TITLE
QA_Preparation of Association Colloid - Micelles and Cleansing Actions of Soaps and Detergents_experiment_magnetic-bead

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#70]
Defect Description :
In the experiment section, the direction of the magnetic bead is different in the converted experiment.

Actual Result :
In the experiment section, the direction of the magnetic bead is different in the converted experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

![qa_csc_i044 a](https://user-images.githubusercontent.com/13479177/33988039-06cf40ea-e0e9-11e7-8c19-8cde2010c6aa.png)
![qa_csc_i044 b](https://user-images.githubusercontent.com/13479177/33988040-070ef51e-e0e9-11e7-8241-8338369a94a9.png)

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
