### ISSUE TITLE
QA_ Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles _experiment_magnetic-bead-movement

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#71]
Defect Description :
In the experiment section, once the magnetic bead is placed in the conical flask the movement of the bead is differing from the original experiment

Actual Result :
In the experiment section, once the magnetic bead is placed in the conical flask the movement of the bead is differing from the original experiment

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

**N/A**

**Comment by blazingeagle1002** [comment]
Lalit sir suggested to ignore it.

**Comment by BSravanthi** [comment]
Closed
