### ISSUE TITLE
QA_Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles_Experiment_magnetic-bead-functionality

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/colloid-and-surface-chemistry-iiith-javascript-lab#9]
Defect Description :
In the experiment section, the magnetic bead revolves up and down in the original experiment. Where as in the converted experiment the bead revolves horizontally. 

Actual Result :
In the experiment section, the magnetic bead revolves up and down in the original experiment. Where as in the converted experiment the bead revolves horizontally. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qacsc_i23](https://user-images.githubusercontent.com/13479177/28312565-3599f3a8-6bd1-11e7-8a2d-1ebb55281a61.png)
![qa_csc_i23](https://user-images.githubusercontent.com/13479177/28312564-35997338-6bd1-11e7-9ba5-c9726d65fa9d.png)

**Comment by blazingeagle1002** [comment]
The issue is approved by Lalit sir

**Comment by BSravanthi** [comment]
closed
